twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: false
    exception_controller: null
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/public/css': css
        '%kernel.project_dir%/public/js': js
        '%kernel.project_dir%/public/images': images

when@test:
    twig:
        strict_variables: true
